#!/usr/bin/env bash
# Koboldcpp build script — P40 (sm_61) e RTX 3050 (sm_86)
# Autogenerated per v1.116 release

set -euo pipefail

# Detect CUDA devices
detect_cuda_devices() {
    if ! command -v nvidia-smi &> /dev/null; then
        echo "ERROR: nvidia-smi not found. CUDA not installed or not accessible."
        exit 1
    fi

    echo "=== CUDA Devices ==="
    nvidia-smi --query-gpu=index,name,memory.total --format=csv,noheader,nounits
    echo ""
}

# Build for specific GPU
build_for_gpu() {
    local gpu_index=$1
    local gpu_name=$2
    local cuda_archs=$3
    local output_dir="build_${gpu_index}"

    echo "=== Building for GPU $gpu_index: $gpu_name ==="
    echo "CUDA_ARCHS=$cuda_archs"

    mkdir -p "$output_dir"
    cd "$output_dir"

    # Clean previous build
    rm -rf *

    # Build with CUDA
    cmake .. \
        -DGGML_CUDA=ON \
        -DCMAKE_CUDA_ARCHITECTURES="$cuda_archs" \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_SHARED_LIBS=OFF \
        -DGGML_CUDA_FAQS=ON

    make -j$(nproc)

    echo "Build completed: $output_dir/"
    cd ..
}

# Main menu
main() {
    detect_cuda_devices

    echo "=== Build Options ==="
    echo "1) Build for Tesla P40 (sm_61)"
    echo "2) Build for RTX 3050 (sm_86)"
    echo "3) Build for both GPUs"
    echo "4) Exit"
    echo ""
    read -p "Select option [1-4]: " choice

    case $choice in
        1)
            build_for_gpu 0 "Tesla P40" "61"
            ;;
        2)
            build_for_gpu 1 "RTX 3050" "86"
            ;;
        3)
            build_for_gpu 0 "Tesla P40" "61"
            build_for_gpu 1 "RTX 3050" "86"
            ;;
        4)
            echo "Exiting."
            exit 0
            ;;
        *)
            echo "Invalid option."
            exit 1
            ;;
    esac

    echo ""
    echo "=== Build Summary ==="
    echo "Build directories created:"
    ls -d build_* 2>/dev/null || echo "No builds completed."
}

main "$@"
